default: &default
  adapter:  postgresql
  encoding: unicode
  pool:     <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  url:      <%= ENV.fetch("DATABASE_URL") %>
  timeout:  5000

development:
  <<: *default
  database: currency_api_development

test:
  <<: *default
  database: currency_api_test

production:
  <<: *default
  database: currency_api_production
